### ISSUE TITLE
How to install on Amazon Linux

### ISSUE THREAD

**Issue by hayd** [lambci/cli#2]
When running on a fresh ec2 after [installing node + npm](http://stackoverflow.com/a/27350635/1240268):

```
$ sudo yum install nodejs npm --enablerepo=epel
$ npm install -g lambci-cli           # installs to local since I have a .npmrc
$ lambci                              # I added .npm/bin to my PATH

/home/andy/.npm/lib/node_modules/lambci-cli/cli.js:17
`
^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

Presumably this isn't pulling in the right version of node or npm?
Would be great to include some installation instructions for ec2.

Thanks!

**Comment by mhart** [comment]
No idea what version of Node.js it's pulling there – what's the output of `node --version`?

`lambci-cli` requires at least Node.js 4.x: https://github.com/lambci/cli/blob/master/package.json#L13

Instructions for installing Node.js on available at nodejs.org: https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora

You can also just:

``` console
curl -sSL https://nodejs.org/dist/v4.6.0/node-v4.6.0-linux-x64.tar.xz | sudo tar -xJ --strip-components=1 -C /usr/local
```

**Comment by hayd** [comment]
Thank you! That link worked perfectly.

(If I try again with a fresh instance I'll note down the steps.)
